name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia √† meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: fonsoodev
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          message: üêç Atualizando anima√ß√£o da cobrinha
          add: "dist/*.svg"
